name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest # Use a Windows runner for cross-compilation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --add-data "index.html;." --add-data "facts.json;." --add-data "images;images" --add-data "sounds;sounds" start_server.py

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: dist/start_server.exe
